#pragma once

#include <string>
#include <stdint.h>
#include <glm.hpp>
#include <unordered_map>
#include <memory>
#include <ogl.h>
#include <vk.h>

namespace dw
{
class Material;

// Non-skeletal vertex structure.
struct Vertex
{
    glm::vec4 position;
    glm::vec4 tex_coord;          // uv0: primary texture coordinates
    glm::vec4 lightmap_tex_coord; // uv1: lightmap UV (generated by xatlas)
    glm::vec4 normal;
    glm::vec4 tangent;
    glm::vec4 bitangent;
};

// SubMesh structure. Currently limited to one Material.
struct SubMesh
{
    std::string name;
    uint32_t    mat_idx;
    uint32_t    index_count;
    uint32_t    base_vertex;
    uint32_t    base_index;
    uint32_t    vertex_count;
    glm::vec3   max_extents;
    glm::vec3   min_extents;
};

class Mesh
{
public:
    using Ptr = std::shared_ptr<Mesh>;

    static bool is_loaded(const std::string& name);

    // Static factory methods.
    // generate_lightmap_uv: automatically generate lightmap UV (uv1) using xatlas
    static Mesh::Ptr load(
#if defined(DWSF_VULKAN)
        vk::Backend::Ptr backend,
#endif
        const std::string& path,
        bool               load_materials       = true,
        bool               is_orca_mesh         = false,
        bool               generate_lightmap_uv = true);
    // Custom factory method for creating a mesh from provided data.
    static Mesh::Ptr load(
#if defined(DWSF_VULKAN)
        vk::Backend::Ptr backend,
#endif
        const std::string&                     name,
        std::vector<Vertex>                    vertices,
        std::vector<uint32_t>                  indices,
        std::vector<SubMesh>                   sub_meshes,
        std::vector<std::shared_ptr<Material>> materials,
        glm::vec3                              max_extents,
        glm::vec3                              min_extents);

    bool set_submesh_material(std::string name, std::shared_ptr<Material> material);
    bool set_submesh_material(uint32_t mesh_idx, std::shared_ptr<Material> material);
    void set_global_material(std::shared_ptr<Material> material);

    // Lightmap UV query
    inline bool     has_lightmap_uvs() const { return m_has_lightmap_uvs; }
    inline uint32_t lightmap_width() const { return m_lightmap_width; }
    inline uint32_t lightmap_height() const { return m_lightmap_height; }

#if defined(DWSF_VULKAN)
    void initialize_for_ray_tracing(vk::Backend::Ptr backend);

    // Rendering-related getters.
    inline vk::Buffer::Ptr                 vertex_buffer() { return m_vbo; }
    inline vk::Buffer::Ptr                 index_buffer() { return m_ibo; }
    inline const vk::VertexInputStateDesc& vertex_input_state_desc() { return m_vertex_input_state_desc; }
    inline vk::AccelerationStructure::Ptr  acceleration_structure() { return m_blas; }
#else
    inline gl::Buffer::Ptr vertex_buffer()
    {
        return m_vbo;
    }
    inline gl::Buffer::Ptr  index_buffer() { return m_ibo; }
    inline gl::VertexArray* mesh_vertex_array()
    {
        return m_vao.get();
    }
#endif

    inline uint32_t id()
    {
        return m_id;
    }
    inline const std::vector<std::shared_ptr<Material>>& materials() { return m_materials; }
    inline const std::vector<SubMesh>&                   sub_meshes() { return m_sub_meshes; }
    inline const std::vector<uint32_t>&                  indices() { return m_indices; }
    inline const std::vector<Vertex>&                    vertices() { return m_vertices; }
    inline std::shared_ptr<Material>&                    material(uint32_t idx) { return m_materials[idx]; }
    inline const glm::vec3&                              max_extents() { return m_max_extents; }
    inline const glm::vec3&                              min_extents() { return m_min_extents; }
    ~Mesh();

private:
    // Private constructor to prevent manual creation.
    Mesh();
    Mesh(
#if defined(DWSF_VULKAN)
        vk::Backend::Ptr backend,
#endif
        const std::string& path,
        bool               load_materials,
        bool               is_orca_mesh,
        bool               generate_lightmap_uv);

    // Internal initialization methods.
    void create_gpu_objects(
#if defined(DWSF_VULKAN)
        vk::Backend::Ptr backend
#endif
    );

    void load_from_disk(
#if defined(DWSF_VULKAN)
        vk::Backend::Ptr backend,
#endif
        const std::string& path,
        bool               load_materials,
        bool               is_orca_mesh);

    // Lightmap UV generation using xatlas (called internally by constructor)
    bool generate_lightmap_uvs();

    // Lightmap cache methods
    static std::string get_lightmap_cache_path(const std::string& mesh_path);
    uint64_t           compute_mesh_hash() const;
    bool               load_lightmap_cache(const std::string& cache_path, uint64_t expected_hash);
    bool               save_lightmap_cache(const std::string& cache_path, uint64_t mesh_hash) const;

private:
    // Mesh cache. Used to prevent multiple loads.
    static std::unordered_map<std::string, std::weak_ptr<Mesh>> m_cache;

    // Mesh geometry.
    uint32_t                               m_id = 0;
    std::vector<std::shared_ptr<Material>> m_materials;
    std::vector<Vertex>                    m_vertices;
    std::vector<uint32_t>                  m_indices;
    std::vector<SubMesh>                   m_sub_meshes;
    glm::vec3                              m_max_extents;
    glm::vec3                              m_min_extents;

    // Lightmap UV generation state
    bool     m_has_lightmap_uvs = false;
    uint32_t m_lightmap_width   = 0;
    uint32_t m_lightmap_height  = 0;

    // GPU resources.
#if defined(DWSF_VULKAN)
    vk::AccelerationStructure::Ptr       m_blas;
    VkAccelerationStructureCreateInfoKHR m_blas_info;
    vk::Buffer::Ptr                      m_vbo;
    vk::Buffer::Ptr                      m_ibo;
    vk::VertexInputStateDesc             m_vertex_input_state_desc;
#else
    gl::VertexArray::Ptr m_vao = nullptr;
    gl::Buffer::Ptr      m_vbo = nullptr;
    gl::Buffer::Ptr      m_ibo = nullptr;
#endif
};
} // namespace dw
